sheetmusic/__init__.py
import atexit
import logging
import os

from apscheduler.schedulers.background import BackgroundScheduler
from flask import Flask

from sheetmusic.db import populate_db

def create_app():
    logging.basicConfig(level=logging.INFO, format="[%(asctime)s] %(levelname)s: %(message)s")

    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'db.sqlite'),
    )

    # load the instance config
    app.config.from_pyfile('config.py', silent=True)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from . import db
    db.init_app(app)

    from . import routes
    app.register_blueprint(routes.routes)

    def automation():
        with app.app_context():
            populate_db()

    scheduler = BackgroundScheduler()
    scheduler.add_job(func=automation, trigger='cron', hour=0, minute=0)
    scheduler.start()

    atexit.register(lambda: scheduler.shutdown())

    return app

sheetmusic/routes.py
import logging
import sqlite3

from flask import Blueprint, g, render_template, request

from sheetmusic.db import get_db

# probably don't need the last two...
routes = Blueprint("routes", __name__, static_folder="static", template_folder="templates")

def get_series() -> list[str]:
    db = get_db()
    try:
        series = db.execute("SELECT DISTINCT series FROM music ORDER BY series ASC").fetchall()
        if not series:
            return []
        return map(lambda x: x["series"], series)
    except sqlite3.OperationalError as e:
        logging.error(e)
        return []

def get_stats() -> tuple:
    db = get_db()
    try:
        metadata = db.execute("SELECT * FROM metadata").fetchone()
        return metadata["last_update"], metadata["num_sheets"]
    except sqlite3.OperationalError as e:
        logging.error(e)
        return "", 0

@routes.before_request
def get_base_data():
    series = get_series()
    last_update, num_sheets = get_stats()
    g.series = series
    g.last_update = last_update
    g.num_sheets = num_sheets

@routes.route("/")
def index():
    if not series:
        return render_template
    return render_template("index.html", series=series)

@routes.route("/series/<path:name>")
def series(name):
    db = get_db()
    sheets = db.execute("SELECT * FROM music WHERE series=? ORDER BY game, title", (name,))

    mapping = {}
    for sheet in sheets:
        if sheet["game"] in mapping:
            mapping[sheet["game"]].append(sheet)
        else:
            mapping[sheet["game"]] = [sheet]

    games = list(mapping.keys())

    return render_template("sheets.html", series=series, name=f"Series: {name}", sheets=mapping, games=games)

@routes.route("/search", methods=["POST"])
def search():
    query = request.form["query"]
    db = get_db()

    try:
        sheets = db.execute("SELECT * FROM music WHERE title LIKE ? OR title_plain LIKE ? OR game LIKE ? OR game_plain LIKE ?",
                            (f"%{query}%", f"%{query}%", f"%{query}%", f"%{query}%"))
    except sqlite3.OperationalError as e:
        logging.error(e)
        sheets = []

    mapping = {}
    for sheet in sheets:
        if sheet["game"] in mapping:
            mapping[sheet["game"]].append(sheet)
        else:
            mapping[sheet["game"]] = [sheet]

    games = list(mapping.keys())

    return render_template("sheets.html", series=series, name=f"Search: {query}", sheets=mapping, games=games)

sheetmusic/templates/base.html
<!doctype html>
<head>
    <title>NinSheetMusic Search</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div id="header">
        <h1><a href="{{ url_for("routes.index") }}">NinSheetMusic</a></h1>
        <div>
            <form method="post" action="/search">
                <input id="query" name="query" type="text" placeholder="Search all songs" required>
            </form>
        </div>
    </div>
    <div id="sidebar">
        {% if g.num_sheets == 0 %}
            <p>No sheet music data. Run <code>python3 -m flask --app sheetmusic init-db</code> to pull the latest data from <a href="ninsheetmusic.org">ninsheetmusic.org</a></p>
        {% else %}
        <ul>
            {% for title in g.series %}
            <li><a href="{{ url_for('routes.series', name=title) }}">{{ title }}</a></li>
            {% endfor %}
        </ul>
        <p title="Updated {{ g.last_update }}">{{ g.num_sheets }} sheets</p>
        {% endif %}
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>

sheetmusic/templates/index.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

sheetmusic/templates/sheets.html
{% extends 'base.html' %}

{% block content %}

<style>
    @media screen and (max-width: 800px) {
        #sidebar {
            display: none;
        }

        #content {
            display: unset;
        }
    }
</style>

{% if g.num_sheets != 0 %}
<h2>{{ name }}</h2>
{% endif %}

<ul>
{% for game in games %}
    <h3>{{ game }} [{{ sheets[game][0]["platform"] }}]</h3>
    {% for sheet in sheets[game] %}
        <li><a href="{{ sheet['url'] }}">{{ sheet["title"] }}</a></li>
    {% endfor %}
{% endfor %}
</ul>

{% endblock %}